### ISSUE TITLE
have error with enter url https://mysite.com/f/grdyf

### ISSUE THREAD

**Issue by raymand211092** [HeroCC/yourls-conditional-urlads#7]
Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /media/drive/www/public/shortlink/user/plugins/yourls-conditional-urlads/plugin.php:25 Stack trace: #0 /media/drive/www/public/shortlink/user/plugins/yourls-conditional-urlads/plugin.php(25): implode() #1 /media/drive/www/public/shortlink/includes/functions-plugins.php(224): check_for_redirect() #2 /media/drive/www/public/shortlink/includes/functions-plugins.php(275): yourls_apply_filter() #3 /media/drive/www/public/shortlink/yourls-loader.php(67): yourls_do_action() #4 {main} thrown in /media/drive/www/public/shortlink/user/plugins/yourls-conditional-urlads/plugin.php on line 25

**Comment by raymand211092** [comment]
Solved change php version for 7.4
